services:
  backend:
    build:
      context: ./course-swap-backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    command: /bin/sh -c "env && node app.js"
    env_file:
      - ./course-swap-backend/.env
    environment:
      - FIREBASE_SERVICE_ACCOUNT
      - APP_PASSWORD
      - MONGO_URI
      - INIT_REFRESH_TOKEN
      - CLIENT_ID
      - CLIENT_SECRET
      - REDIRECT_URI
    networks:
      - app-network
  frontend:
    build: 
      context: ./course-swap-app
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    env_file:
      - ./course-swap-app/.env 
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
