services:
  backend:
    image: tanmaysalunke/backend:latest
    build:
      context: ./course-swap-backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    command: /bin/sh -c "env && node app.js"
    environment:
      MONGO_URI: ${MONGO_URI}
      APP_PASSWORD: ${APP_PASSWORD}
      FIREBASE_SERVICE_ACCOUNT: ${FIREBASE_SERVICE_ACCOUNT}
      INIT_REFRESH_TOKEN: ${INIT_REFRESH_TOKEN}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      REDIRECT_URI: ${REDIRECT_URI}
    networks:
      - app-network
  frontend:
    image: tanmaysalunke/frontend:latest
    build: 
      context: ./course-swap-app
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
