name: Test SCP Command to EC2

on:
  push:
    branches:
      - master

jobs:
  test-scp:
    runs-on: ubuntu-latest
    steps:
      - name: Test SSH connection and SCP file to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "Disabling strict host key checking..."
            mkdir -p ~/.ssh
            echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

            echo "Testing SCP command..."
            echo "This is a test file." > test_file.txt
            scp -v -o StrictHostKeyChecking=no test_file.txt ubuntu@${{ secrets.HOST }}:/home/ubuntu/test_file.txt

            echo "Checking if the file was transferred..."
            ls -l /home/ubuntu/test_file.txt
            echo "SCP test completed."
