name: Test SSH and SCP

on:
  push:
    branches:
      - master

jobs:
  test-ssh-scp:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and SCP Test
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "Attempting to create a simple file on EC2..."
            echo "This is a test from GitHub Actions." > ~/testfile.txt
            echo "File creation success, listing directory contents..."
            ls -l ~/
            echo "Now attempting to SCP a file..."
            echo "Sample content for SCP test" > sample.txt
            scp -v -o StrictHostKeyChecking=no sample.txt ubuntu@${{ secrets.HOST }}:/home/ubuntu/
            echo "SCP command executed, checking file presence..."
            ls -l /home/ubuntu/sample.txt
