name: Test Docker Commands Execution

on:
  push:
    branches:
      - master

jobs:
  docker-commands-test:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Commands Test
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "Pulling a Docker test image..."
            docker pull hello-world
            echo "Running Docker hello-world image..."
            docker run hello-world
            echo "Docker commands executed successfully."
