name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        run: |
          docker build -t tanmaysalunke/myapp-frontend:${{ github.sha }} ./course-swap-app
          docker build -t tanmaysalunke/myapp-backend:${{ github.sha }} ./course-swap-backend
          docker push tanmaysalunke/myapp-frontend:${{ github.sha }}
          docker push tanmaysalunke/myapp-backend:${{ github.sha }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker pull tanmaysalunke/myapp-frontend:${{ github.sha }}
            docker pull tanmaysalunke/myapp-backend:${{ github.sha }}
            docker-compose -f /var/www/docker-compose.yml up -d
