name: Test File Creation and SCP Transfer

on:
  push:
    branches:
      - master

jobs:
  scp-transfer-test:
    runs-on: ubuntu-latest
    steps:
      - name: SCP File Transfer Test
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "Creating a test file..."
            echo "This is a test file created by GitHub Actions." > testfile.txt
            echo "Transferring file..."
            scp -o StrictHostKeyChecking=no testfile.txt ubuntu@${{ secrets.HOST }}:/home/ubuntu/testfile.txt
            echo "File transfer successful."
            rm testfile.txt  # Cleanup the local test file
