name: Combined Steps Test

on:
  push:
    branches:
      - master

jobs:
  combined-test:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Setup and Environment File Test
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "Setting up SSH..."
            mkdir -p ~/.ssh
            echo "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
            echo "Creating backend_env file..."
            echo "APP_PASSWORD=${{ secrets.APP_PASSWORD }}" > backend_env
            echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> backend_env
            echo "INIT_REFRESH_TOKEN=${{ secrets.INIT_REFRESH_TOKEN }}" >> backend_env
            echo "CLIENT_ID=${{ secrets.CLIENT_ID }}" >> backend_env
            echo "CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}" >> backend_env
            echo "REDIRECT_URI=${{ secrets.REDIRECT_URI }}" >> backend_env
            echo "FIREBASE_SERVICE_ACCOUNT=${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" >> backend_env
            echo "Transferring backend_env to EC2..."
            scp -o StrictHostKeyChecking=no backend_env ubuntu@${{ secrets.HOST }}:/home/ubuntu/backend_env
            echo "Running Docker containers..."
            docker pull ${{ secrets.DOCKER_USERNAME }}/course-swap-app:latest
            docker run -d -p 3000:80 --env-file /home/ubuntu/backend_env ${{ secrets.DOCKER_USERNAME }}/course-swap-app:latest
