name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Set up Docker
      #   uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        run: |
          docker build -t tanmaysalunke/myapp-frontend:${{ github.sha }} ./course-swap-app
          docker build -t tanmaysalunke/myapp-backend:${{ github.sha }} ./course-swap-backend
          docker push tanmaysalunke/myapp-frontend:${{ github.sha }}
          docker push tanmaysalunke/myapp-backend:${{ github.sha }}

  deploy:
    needs: build
    runs-on: aws-ec2
    steps:
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Pull images from Docker Hub
        run: |
          docker pull tanmaysalunke/myapp-frontend:${{ github.sha }}
          docker pull tanmaysalunke/myapp-backend:${{ github.sha }}

      - name: Stop and remove old frontend container
        run: |
          docker rm -f reactFrontendContainer || true

      - name: Stop and remove old backend container
        run: |
          docker rm -f reactBackendContainer || true

      - name: Run the frontend Docker container
        run: |
          docker run -d -p 3000:80 --name reactFrontendContainer tanmaysalunke/myapp-frontend:${{ github.sha }}

      - name: Run the backend Docker container
        run: |
          docker run -d -p 5000:5000 --name reactBackendContainer tanmaysalunke/myapp-backend:${{ github.sha }}
