name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push frontend image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/course-swap-app:latest ./course-swap-app
          docker push ${{ secrets.DOCKER_USERNAME }}/course-swap-app:latest

      - name: Build and push backend image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/course-swap-backend:latest ./course-swap-backend
          docker push ${{ secrets.DOCKER_USERNAME }}/course-swap-backend:latest

      - name: Set up Docker secrets on EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e

            # Remove existing secrets (if any)
            docker secret rm app_password || true
            docker secret rm mongo_uri || true
            docker secret rm init_refresh_token || true
            docker secret rm client_id || true
            docker secret rm client_secret || true
            docker secret rm redirect_uri || true
            docker secret rm firebase_service_account || true
              
            # Create new secrets
            echo "${{ secrets.APP_PASSWORD }}" | docker secret create app_password -
            echo "${{ secrets.MONGO_URI }}" | docker secret create mongo_uri -
            echo "${{ secrets.INIT_REFRESH_TOKEN }}" | docker secret create init_refresh_token -
            echo "${{ secrets.CLIENT_ID }}" | docker secret create client_id -
            echo "${{ secrets.CLIENT_SECRET }}" | docker secret create client_secret -
            echo "${{ secrets.REDIRECT_URI }}" | docker secret create redirect_uri -
            echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" | docker secret create firebase_service_account -

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/course-swap-app:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/course-swap-backend:latest

            # Stop existing containers
            docker ps -q --filter ancestor=***/course-swap-app:latest | xargs -r docker stop
            docker ps -q --filter ancestor=***/course-swap-backend:latest | xargs -r docker stop
              
            # Remove existing containers
            docker ps -a -q --filter ancestor=***/course-swap-app:latest | xargs -r docker rm
            docker ps -a -q --filter ancestor=***/course-swap-backend:latest | xargs -r docker rm

            # Run the frontend container
            docker run -d -p 3000:80 ***/course-swap-app:latest

            # Run the backend container with environment file
            docker run -d -p 5000:5000 \
              --env-file /run/secrets/backend_env \
              ***/course-swap-backend:latest
