name: Test Basic SSH Connectivity

on:
  push:
    branches:
      - master

jobs:
  ssh-connection-test:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Connection Test
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "SSH connection established successfully."
